# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          servers: '[{"id": "ossrh", "username": OSSRH_USERNAME, "password": OSSRH_PASSWORD}]'
      - id: install-secret-key
        name: Install GPG Private Key
        run: |
          cat <(echo -e "${{secrets.GPG_PRIVATE_KEY}}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Build with Maven
        run: mvn -B deploy release:prepare release:perform --batch-mode -Prelease -Dgpg.passphrase=${{secrets.GPG_PASSPHRASE}} --file pom.xml
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
          GIT_USERNAME: ${{secrets.GIT_USERNAME}}
          GIT_PASSWORD: ${{secrets.GIT_PASSWORD}}
